[0m14:57:53.115658 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D0FF8769F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D0FD990740>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D0FD5197C0>]}


============================== 14:57:53.123669 | 78112da7-07c5-49b3-b600-45cf05dad8de ==============================
[0m14:57:53.123669 [info ] [MainThread]: Running with dbt=1.9.2
[0m14:57:53.125656 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\KARTIKEY\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt init snow_dbt_prj', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m14:57:53.159746 [debug] [MainThread]: Starter project path: C:\Users\KARTIKEY\OneDrive\Desktop\fidelity\snow_dbt\snow\Lib\site-packages\dbt\include\starter_project
[0m14:57:53.188740 [info ] [MainThread]: 
Your new dbt project "snow_dbt_prj" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m14:57:53.192742 [info ] [MainThread]: Setting up your profile.
[0m15:00:18.967527 [info ] [MainThread]: Profile snow_dbt_prj written to C:\Users\KARTIKEY\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m15:00:18.977529 [debug] [MainThread]: Command `dbt init` succeeded at 15:00:18.976543 after 146.06 seconds
[0m15:00:18.981534 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D0FF9EEBD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D0FFBC32C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D0FF5B9EE0>]}
[0m15:00:18.985529 [debug] [MainThread]: Flushing usage events
[0m15:00:20.198087 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:00:29.087590 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D058CB6690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D058CB62A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D058CB75C0>]}


============================== 15:00:29.094621 | 290c8cd9-24c6-4032-bb33-fa5f6d5e7eb5 ==============================
[0m15:00:29.094621 [info ] [MainThread]: Running with dbt=1.9.2
[0m15:00:29.095614 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\KARTIKEY\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt debug', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m15:00:29.130628 [info ] [MainThread]: dbt version: 1.9.2
[0m15:00:29.131594 [info ] [MainThread]: python version: 3.12.2
[0m15:00:29.132594 [info ] [MainThread]: python path: C:\Users\KARTIKEY\OneDrive\Desktop\fidelity\snow_dbt\snow\Scripts\python.exe
[0m15:00:29.133593 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m15:00:29.143597 [info ] [MainThread]: Error importing adapter: No module named 'dbt.adapters.mysql'
[0m15:00:29.147011 [info ] [MainThread]: Error importing adapter: No module named 'dbt.adapters.mysql'
[0m15:00:29.739603 [info ] [MainThread]: Using profiles dir at C:\Users\KARTIKEY\.dbt
[0m15:00:29.741590 [info ] [MainThread]: Using profiles.yml file at C:\Users\KARTIKEY\.dbt\profiles.yml
[0m15:00:29.742586 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\KARTIKEY\OneDrive\Desktop\fidelity\snow_dbt\dbt_project.yml
[0m15:00:29.745096 [info ] [MainThread]: Configuration:
[0m15:00:29.746108 [info ] [MainThread]:   profiles.yml file [[31mERROR invalid[0m]
[0m15:00:29.747107 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m15:00:29.748104 [info ] [MainThread]: Required dependencies:
[0m15:00:29.748104 [debug] [MainThread]: Executing "git --help"
[0m15:00:29.826973 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone      Clone a repository into a new directory\n   init       Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add        Add file contents to the index\n   mv         Move or rename a file, a directory, or a symlink\n   restore    Restore working tree files\n   rm         Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect     Use binary search to find the commit that introduced a bug\n   diff       Show changes between commits, commit and working tree, etc\n   grep       Print lines matching a pattern\n   log        Show commit logs\n   show       Show various types of objects\n   status     Show the working tree status\n\ngrow, mark and tweak your common history\n   backfill   Download missing objects in a partial clone\n   branch     List, create, or delete branches\n   commit     Record changes to the repository\n   merge      Join two or more development histories together\n   rebase     Reapply commits on top of another base tip\n   reset      Reset current HEAD to the specified state\n   switch     Switch branches\n   tag        Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch      Download objects and refs from another repository\n   pull       Fetch from and integrate with another repository or a local branch\n   push       Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m15:00:29.827972 [debug] [MainThread]: STDERR: "b''"
[0m15:00:29.828975 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m15:00:29.829973 [info ] [MainThread]: Connection test skipped since no profile was found
[0m15:00:29.830983 [info ] [MainThread]: [31m2 checks failed:[0m
[0m15:00:29.832982 [info ] [MainThread]: Could not load dbt_project.yml
Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "dbt_mysql_new", target "dev" invalid: Runtime Error
    Could not find adapter type mysql!

Runtime Error
  Credentials in profile "nestedquery", target "dev" invalid: Runtime Error
    Could not find adapter type mysql!


[0m15:00:29.834984 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\KARTIKEY\OneDrive\Desktop\fidelity\snow_dbt\dbt_project.yml> not found

[0m15:00:29.838996 [debug] [MainThread]: Command `dbt debug` failed at 15:00:29.837981 after 0.96 seconds
[0m15:00:29.840982 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D058639160>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D0584C2270>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D058478E30>]}
[0m15:00:29.841984 [debug] [MainThread]: Flushing usage events
[0m15:00:30.795511 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:03:22.025573 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002CC46740530>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002CC49249A00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002CC470F5070>]}


============================== 16:03:22.033996 | a6b0e8d4-b0ca-490b-ad16-5be2cef112b5 ==============================
[0m16:03:22.033996 [info ] [MainThread]: Running with dbt=1.9.2
[0m16:03:22.034992 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\KARTIKEY\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt run', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m16:03:22.035993 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\KARTIKEY\OneDrive\Desktop\fidelity\snow_dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:03:22.039517 [debug] [MainThread]: Command `dbt run` failed at 16:03:22.038505 after 0.18 seconds
[0m16:03:22.040517 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002CC489E02C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002CC46740530>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002CC48F8FDA0>]}
[0m16:03:22.040517 [debug] [MainThread]: Flushing usage events
[0m16:03:23.016973 [debug] [MainThread]: An error was encountered while trying to flush usage events
